# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-15 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('editor', models.CharField(choices=[('Marvel', 'Marvel'), ('DC', 'Detective Comics')], default='Marvel', max_length=100)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='hero',
            options={'ordering': ('name',)},
        ),
        migrations.RenameField(
            model_name='hero',
            old_name='movie',
            new_name='mainTeam',
        ),
        migrations.AddField(
            model_name='heroteam',
            name='heroes',
            field=models.ManyToManyField(to='hero.Hero'),
        ),
    ]
